APP_NAME: '1024'
EXPIRED_DATE: '20201001'
SECRET_KEY_BASE: 6f95fe8b03308d3a48d69cb3dcf8d4bdff6bf7b9e245e785aed07f568bfdf8440523b567fce1a1f753519bf7e481d4937d2e823b65d44158b687ad8f1b873c02
REDIS_URL: redis://localhost:6379/1

# Register limit
REGISTER_LIMIT: '5'

# Google reCaptcha
RECAPTCHA_KEY:
RECAPTCHA_SECRET:

# Devise
DEVISE_SECRET_KEY: b7168107d787ee2108d0b19e5aee126a597b8cf6a27b931ddfaef2d25d71ddc9917856e886c6f9a3f2701d6e5ab457aafcc136463fc76fe6813c5cf866c1c6ea
DEVISE_PEPPER_KEY: 504588f32ac13b0e0cdc7708f8f7cb0caa0b27e6cb49aab9b61e5e8c5df69c8cef7afe136063746d21d5ed43025a74152161a929301dcbf2b643eea05eb11a8f

# OmniAuth
GITHUB_KEY:
GITHUB_SECRET:
FACEBOOK_KEY:
FACEBOOK_SECRET:
TWITTER_KEY:
TWITTER_SECRET:

# Rack::Attack
ATTACK_LIMIT: '10'
ATTACK_PERIOD: '5'
ATTACK_MESSAGE: 访问频率过高，请稍后再试。
ATTACK_BLOCK_IP:

DATABASE_NAME: '1024'
DATABASE_USERNAME: root
DATABASE_PASSWORD:

development:
  DATABASE_USERNAME: root
  DATABASE_PASSWORD:

test:
  DATABASE_USERNAME: root
  DATABASE_PASSWORD:

production:
  DATABASE_USERNAME: root
  DATABASE_PASSWORD: